#开发环境配置

#配置服务器端口号
server:
  port: 8098

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Aa1203948162
#redis配置
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 10000
#mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.example.springbootshirojwt.model

#日志相关配置
#对mybatis日志的配置
logging:
  level:
    com:
      example:
        springbootshirojwt:
          mapper: debug





